### ISSUE TITLE
I don't think this is considered as a finding

### ISSUE THREAD

**Issue by vletoux** [l0ss/Grouper2#89]
I found this in an assessment.

```
{
          "Privilege Rights": {
            "SeLoadDriverPrivilege": {
              "S-1-5-32-545": "BUILTIN\\Utilisateurs",
              "Description": "Required to load or unload a device driver. "
}
```

I don't think this is reported as "Interesting" but maybe I'm wrong.
In this case the SeLoadDriverPrivilege can be used for privilege escalation and it is granted to everyone.
(See the slides of Andrea for more details)

**Comment by l0ss** [comment]
![image](https://user-images.githubusercontent.com/24580473/60755636-f61eef00-a024-11e9-849f-5462eda2506e.png)

It's definitely marked as 'interesting' within the code, as seen by the "I" highlighted in red above, which gets checked in AssessPrivRights.cs on line 37. If you're able to provide any example data that would help.
