### ISSUE TITLE
Ideas, global review

### ISSUE THREAD

**Issue by klettier** [l0ss/Grouper2#92]
Here is a grouping of ideas for a better architecture

## Global

* Split console project into two projects -> lib + Console
  * Allow produce a separate nuget package for your lib
    * Allow people to use and extend your lib instead of using an executable
* Use dependency injection everywhere
  * Allow behavior extension
  * Do not rely on static, e.g. ```Console.Error.WriteLine``` for log
  * Rely on ```interface``` and not on concrete class
    * Allow better testing
* ~~Migrate to [new sdk](https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/) ```csproj```~~
* ~~Is targeting .net framework 4.0 still needed ?~~

## GrouperPlan.cs

* Split plan parsing from plan execution
  * ```ParseCommandLineArguments``` method could be static pure function

**Comment by l0ss** [comment]
Unfortunately targeting .NET 4.0 is necessary, to ensure it'll run on whatever wheezy shitbox the user happens to pop a shell on.

I don't have any particular objections to any of the other items above if you think they're worth implementing, but my focus in my (very) limited free time is on getting the dev branch working properly, then tuning existing features and implementing new ones.

**Comment by klettier** [comment]
Ok, just tell me/list what is missing to be able to do the merge with master branch

**Comment by l0ss** [comment]
I've created a short list of issues with the 'dev' tag, Sh3r4's gonna create a more detailed list of issues based on her notes. Should provide plenty to work on.

**Comment by l0ss** [comment]
closed
